name: Publish IP Tester

on:
  workflow_dispatch:
    inputs:
      dryrun:
        type: boolean
        default: false

env:
  BASE_VERSION: '1.0'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - name: Build
        env:
          IPI_DATA_FILE_URL: ${{ secrets.IPI_DATA_FILE_URL }}
        run: |
          printf -v tag '%s-%(%y%m%dT%H%M)T' "$BASE_VERSION" -1
          docker build --secret id=IPI_DATA_FILE_URL --platform=linux/amd64 --tag=51degrees/ipitester:{latest,"$tag"} .
      - name: Publish
        if: ${{ !inputs.dryrun }}
        env:
          USER: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u "$USER" --password-stdin <<<"$PASSWORD" && docker push -a 51degrees/ipitester
