name: Publish Minicloud

on:
  workflow_dispatch:
    inputs:
      dryrun:
        type: boolean
        default: false

env:
  BASE_VERSION: '1.0'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - name: Build
        env:
          IPI_DATA_FILE_URL: ${{ secrets.IPI_DATA_FILE_URL }}
        run: |
          printf -v tag '%s-%(%y%m%dT%H%M)T' "$BASE_VERSION" -1
          docker build --secret id=IPI_DATA_FILE_URL --tag=51degrees/minicloud:{latest,"$tag"} -f Examples/OnPremise/Mixed/GettingStarted-API/Dockerfile .
      - name: Publish
        if: ${{ !inputs.dryrun }}
        env:
          USER: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u "$USER" --password-stdin <<<"$PASSWORD" && docker push -a 51degrees/minicloud

